env-development: ${ENV_DEVELOPMENT:LOCAL}

spring:
  application:
    name: SalaryTime
  data:
    mongodb:
      authentication-database: admin
      host: ${DATASOURCE_HOST:localhost}
      port: ${DATASOURCE_PORT:27017}
      database: salary-time-db
      username: ${DATASOURCE_USERNAME:salary-time}
      password: ${DATASOURCE_PASSWORD}

api:
  host: ${API_HOST:http://localhost:8080}
