spring:
  application:
    name: SalaryTime
  data:
    mongodb:
      host: {DATASOURCE_HOST:localhost}
      port: {DATASOURCE_PORT:27017}
      database: salary-time-db
      username: ${DATASOURCE_USERNAME:salary-time}
      password: ${DATASOURCE_PASSWORD}
